### ISSUE TITLE
 Showing All Messages The package product 'ComposableArchitecture' requires minimum platform version 10.15 for the macOS platform, but this target supports 10.10

### ISSUE THREAD

**Issue by saroar** [darrarski/swift-composable-presentation#2]
I am using this package inside another package 
when I start the test I am getting this error I can't run my test 
here is my app link https://github.com/AddaMeSPB/AddaMeIOS/blob/feature/git_workflow/AddameSPM/Tests/EventViewTests/EventsViewTests.swift#L19

## Steps to reproduce
you can just grab my app and run test

## Actual behavior
test should run without any error
## Attachments
<img width="726" alt="Screenshot 2021-09-15 at 15 47 31" src="https://user-images.githubusercontent.com/8770772/133436080-8b0d53cf-1a9b-4300-ad57-31b8d2c9563d.png">

Showing All Messages The package product 'ComposableArchitecture' requires minimum platform version 10.15 for the macOS platform, but this target supports 10.10

**Comment by darrarski** [comment]
This is not a bug. The `swift-composable-presentation` package does not support the macOS platform. You might need to validate your project configuration if you're not supporting macOS too. However, if you need macOS platform support, the `swift-composable-presentation` package has to be updated.

I've created an issue for adding macOS support to the package: #3

You are welcome to create a pull request that adds macOS platform support.
