### ISSUE TITLE
ForEachStoreExample Crash

### ISSUE THREAD

**Issue by jhchenchong** [darrarski/swift-composable-presentation#28]
## Summary

When I click on Add Timer 16 times it crashed

## Steps to reproduce

1. Go to ForEachStoreExample
2. Click on Add Timer at least 16 times

**Comment by darrarski** [comment]
I have updated dependencies and released version 0.5.1. I'm no longer able to reproduce the crash. @jhchenchong please let me know if this solves the problem for you as well.

**Comment by jhchenchong** [comment]
> I have updated dependencies and released version 0.5.1. I'm no longer able to reproduce the crash. @jhchenchong please let me know if this solves the problem for you as well.

It works now, Thanks!
